apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp-devsu
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30800
