apiVersion: apps/v1
kind: Deployment
metadata:
  name: postulacion-devsu
  namespace: myapp-devsu
  labels:
    app: web
spec:
  selector:
    matchLabels:
      postulacion: devsu
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        postulacion: devsu
    spec:
      containers:
        - name: myapp
          image: 'public.ecr.aws/z6a3d9k0/postulacion-devsu:807ef323f9ac8bb82e9727a51dd7d28cee2db08d'
          imagePullPolicy: Always
          ports:
            - name: gunicorn
              containerPort: 8000
              protocol: TCP
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret-key
                  key: DJANGO_SECRET_KEY
          envFrom:
          - configMapRef:
              name: myapp-config
